/** Semua teks UI — Bahasa Indonesia */
export const id = {
  app: {
    name: "Yono Catering",
    tagline: "Kantor COOFIS nih BOOSSS!!!",
    description: "Menu harian dan preferensi makan untuk rumah tangga Yono.",
  },
  nav: {
    kitchen: "Dapur",
    settings: "Pengaturan",
    home: "Beranda",
    logout: "Keluar",
  },
  login: {
    title: "Masuk",
    avatarAlt: "Pak Yono",
    heading: "Yono Catering",
    subtitle:
      "Pilih nama dan PIN untuk lihat menu hari ini dan jawab sebelum batas waktu.",
    who: "Siapa kamu?",
    pickName: "Pilih nama",
    pin: "PIN",
    submit: "Masuk dapur",
    submitting: "Sedang masuk…",
    noUsers: "Belum ada pengguna.",
    seedHint: "Jalankan npm run db:push && npm run db:seed dulu.",
    errorNamePin: "Pilih nama dan masukkan PIN.",
    errorWrong: "Nama atau PIN salah.",
  },
  time: {
    hour: "Jam",
    minute: "Menit",
    clear: "Pakai batas standar",
    setCustom: "Atur jam khusus",
    quick: "Cepat",
    less: "Kurangi",
    more: "Tambah",
  },
  calendar: {
    pickDay: "Pilih hari",
    pickedDay: "Hari dipilih",
    prevMonth: "Bulan sebelumnya",
    nextMonth: "Bulan berikutnya",
    today: "Ke hari ini",
    weekdays: ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"],
  },
  home: {
    todaysDish: "Menu hari ini",
    note: "Catatan",
    respondBefore: "Jawab sebelum",
    locked: "terkunci",
    yourStatus: "Status kamu",
    yes: "Ya",
    swap: "Ganti",
    noMenu: "Belum ada menu untuk hari ini.",
    noMenuHint: "Cek lagi setelah Pak Yono posting menu.",
    pushOn: "Pengingat aktif",
    pushEnable: "Aktifkan pengingat",
  },
  response: {
    title: "Jawaban kamu",
    locked: "Jawaban sudah terkunci untuk hari ini.",
    lockedHint: "Batas waktu sudah lewat — tidak bisa diubah lagi.",
    wantDish: "Mau menu hari ini?",
    yes: "Mau",
    yesHint: "Ikut menu Pak Yono",
    noSwap: "Ganti",
    noSwapHint: "Mau menu lain",
    swapLabel: "Mau diganti apa?",
    swapPlaceholder: "contoh: ayam, mie goreng",
    noteLabel: "Preferensi makan",
    notePlaceholder: "atau tulis sendiri…",
    noteQuick: "Pilih cepat",
    notePresets: ["Pedas", "Tidak pedas", "Tanpa cabe", "Nasi banyak"] as const,
    saved: "Tersimpan!",
    saving: "Menyimpan…",
    submit: "Simpan jawaban",
    yourAnswer: "Jawabanmu",
    eating: "Makan",
    notEating: "Ganti jadi",
    noNote: "Tanpa catatan",
    fromPreference: (dish: string) => `Diisi dari preferensimu untuk ${dish}`,
    savePreference: (dish: string) => `Simpan sebagai preferensi untuk ${dish}`,
  },
  preferences: {
    title: "Preferensi menu",
    hint: "Atur jawaban otomatis kalau Pak Yono posting menu ini.",
    forDish: (dish: string) => `Kalau menu ${dish}`,
    unset: "Belum diatur",
    follow: "Ikut menu",
    swapTo: (dish: string) => `Ganti jadi ${dish}`,
    saved: "Preferensi tersimpan!",
    saving: "Menyimpan…",
    save: "Simpan preferensi",
    remove: "Hapus preferensi",
    removed: "Preferensi dihapus",
  },
  yono: {
    kitchen: "Dapur",
    liveTally: "Ringkasan live",
    cutoff: "Batas waktu",
    locked: "terkunci",
    open: "masih buka",
    emptyTally: "Posting menu dulu untuk mulai kumpulin jawaban.",
    dishLabel: "Menu hari ini",
    dishPlaceholder: "contoh: bebek, nasi goreng",
    noteLabel: "Catatan Pak Yono (opsional)",
    notePlaceholder: "contoh: tambah sayur",
    cutoffOverride: "Batas waktu khusus (JJ:MM, opsional)",
    posted: "Menu diposting!",
    posting: "Memposting…",
    update: "Perbarui menu",
    post: "Posting menu",
    dishQuick: "Pilih cepat",
  },
  settings: {
    title: "Pengaturan",
    standingCutoff: "Batas waktu standar (JJ:MM)",
    reminderTime: "Jam pengingat (JJ:MM)",
    saved: "Tersimpan!",
    saveTimes: "Simpan jam",
    members: "Anggota",
    addMember: "Tambah anggota",
    name: "Nama",
    initialPin: "PIN awal",
    memberAdded: "Anggota ditambahkan!",
    add: "Tambah",
    newPin: "PIN baru",
    resetPin: "Reset PIN",
    pinUpdated: "PIN diperbarui",
    remove: "Hapus",
    defaultDishes: "Menu default",
    defaultDishesHint: "Pak Yono tinggal klik saat posting — anggota bisa atur preferensi per menu.",
    addDish: "Tambah menu",
    dishName: "Nama menu",
    dishAdded: "Menu ditambahkan!",
    dishRemoved: "Menu dihapus",
  },
  errors: {
    missingDay: "Hari tidak ditemukan.",
    swapRequired: "Tulis menu pengganti kalau pilih Tidak.",
    noMenu: "Belum ada menu untuk hari ini.",
    locked: "Jawaban sudah terkunci hari ini.",
    dishRequired: "Menu wajib diisi.",
    cutoffFormat: "Batas waktu harus format JJ:MM.",
    timeFormat: "Jam harus format JJ:MM.",
    namePinRequired: "Nama dan PIN wajib diisi.",
    pinMinLength: "PIN minimal 4 digit.",
    nameTaken: "Nama sudah dipakai.",
    memberNotFound: "Anggota tidak ditemukan.",
    memberPinRequired: "Anggota dan PIN wajib diisi.",
    dishExists: "Menu ini sudah ada di daftar.",
  },
  push: {
    morningTitle: "Selamat pagi, Pak Yono",
    morningBody: "Menu hari ini apa, Pak Yono?",
    menuTitle: "Menu diposting",
    menuBody: (dish: string, cutoff: string) =>
      `Hari ini: ${dish}. Jawab sebelum ${cutoff}.`,
    defaultTitle: "Yono Catering",
  },
  tally: {
    empty: "Belum ada jawaban",
    swap: "ganti",
    portion: (count: number, dish: string) => `${count} ${dish}`,
  },
} as const;
