/** Semua teks UI: Bahasa Indonesia */
export const id = {
  app: {
    name: "Yono Catering",
    tagline: "Lek ate mangan, list-en rek!",
    description:
      "Buat yang belum tahu, ini aplikasi buat bantu Pak Yono ngumpulin pesenan makan siang dari kita-kita. Jadi Pak Yono bisa masak sesuai jumlah yang dibutuhkan aja, gak kebanyakan atau kekurangan. Kita juga bisa kasih catatan kalau mau, misal pedas atau gak pakai cabe. Pokoknya biar makan siangnya makin enak dan sesuai selera kita semua deh!",
  },
  nav: {
    kitchen: "Dapur",
    settings: "Pengaturan",
    users: "Pengguna",
    preferences: "Preferensi",
    home: "Menu Hari Ini",
    logout: "Keluar",
  },
  login: {
    title: "Masuk",
    avatarAlt: "Pak Yono",
    heading: "Yono Catering",
    subtitle:
      "Pilih nama dan PIN untuk lihat menu hari ini dan jawab sebelum batas waktu.",
    who: "Siapa kamu?",
    pickName: "Pilih nama",
    pin: "PIN",
    submit: "Masuk dapur",
    submitting: "Sedang masuk…",
    noUsers: "Belum ada pengguna.",
    seedHint: "Jalankan npm run db:push && npm run db:seed dulu.",
    errorNamePin: "Pilih nama dan masukkan PIN.",
    errorWrong: "Nama atau PIN salah.",
  },
  time: {
    hour: "Jam",
    minute: "Menit",
    clear: "Pakai batas standar",
    setCustom: "Atur jam khusus",
    less: "Kurangi",
    more: "Tambah",
    quick: "Pilihan cepat:",
  },
  calendar: {
    pickDay: "Pilih hari",
    pickedDay: "Hari yang dipilih",
    prevMonth: "Bulan sebelumnya",
    nextMonth: "Bulan berikutnya",
    today: "Hari ini",
    weekdays: ["Sen", "Sel", "Rab", "Kam", "Jum", "Sab", "Min"],
  },
  home: {
    todaysDish: "Menu hari ini",
    note: "Catatan",
    respondBefore: "Jawab sebelum",
    locked: "terkunci",
    yourStatus: "Status kamu",
    yes: "Ya",
    swap: "Tidak",
    noMenu: "Belum ada menu untuk hari ini.",
    noMenuHint: "Cek lagi setelah Pak Yono posting menu.",
    pushOn: "Pengingat aktif",
    pushEnable: "Aktifkan pengingat",
  },
  response: {
    title: "Jawaban Kamu",
    locked: "Jawaban sudah terkunci untuk hari ini.",
    lockedHint: "Batas waktu untuk hari ini sudah lewat.",
    yourAnswer: "Jawaban kamu",
    eating: "Ikut makan",
    notEating: "Tidak ikut makan",
    noNote: "Tanpa catatan",
    fromPreference: (dish: string) => `Diisi otomatis dari preferensi kamu untuk ${dish}`,
    wantDish: "Mau menu hari ini?",
    yes: "Ya",
    yesHint: "Ikut makan menu hari ini",
    no: "Tidak",
    noHint: "Tidak ikut makan hari ini",
    noSwap: "Tidak",
    noSwapHint: "Tidak ikut makan hari ini",
    swapLabel: "Menu pengganti",
    swapPlaceholder: "contoh: ayam",
    noteLabel: "Catatan (opsional)",
    noteQuick: "Pilihan cepat:",
    notePresets: ["Porsi banyak", "Pedas", "Tanpa cabe", "Kuah dipisah", "Bungkus"],
    notePlaceholder: "contoh: pedas, tanpa cabe",
    chooseVariant: "Pilih Varian Menu",
    variantRequired: "Wajib memilih salah satu varian menu.",
    savePreference: (dish: string) => `Ingat pilihan ini sebagai preferensi untuk ${dish}`,
    saved: "Tersimpan!",
    saving: "Menyimpan…",
    submit: "Simpan jawaban",
  },
  preferences: {
    title: "Preferensi Menu Bawaan",
    hint: "Atur pilihan otomatis kamu setiap kali menu ini muncul.",
    unset: "Belum diatur",
    yes: "Ya",
    yesHint: "Ikut makan",
    no: "Tidak",
    noHint: "Tidak ikut makan",
    follow: "Ikut makan",
    skip: "Tidak ikut makan",
    chooseVariantDefault: "Pilihan Varian Default",
    swapTo: (dish: string) => `Ganti ${dish}`,
    forDish: (dish: string) => `Preferensi untuk ${dish}`,
    saved: "Preferensi tersimpan!",
    saving: "Menyimpan…",
    save: "Simpan preferensi",
    removed: "Preferensi dihapus!",
    remove: "Hapus preferensi",
  },
  yono: {
    kitchen: "Dapur",
    liveTally: "Ringkasan Pesanan",
    cutoff: "Batas waktu",
    locked: "terkunci",
    open: "masih buka",
    emptyTally: "Posting menu dulu untuk mulai kumpulin jawaban.",
    dishLabel: "Menu hari ini",
    dishQuick: "Pilihan cepat:",
    dishPlaceholder: "contoh: bebek, nasi goreng",
    noteLabel: "Catatan Pak Yono (opsional)",
    notePlaceholder: "contoh: tambah sayur",
    subDishesLabel: "Pilihan sub-menu / varian (opsional, pisahkan koma)",
    subDishesPlaceholder: "contoh: Bakmi Goreng, Bakmi Godhog, Nasi Goreng",
    subDishesPrefix: "Varian:",
    cutoffOverride: "Batas waktu khusus (JJ:MM, opsional)",
    posted: "Menu diposting!",
    posting: "Memposting…",
    update: "Perbarui menu",
    post: "Posting menu",
    allAnswered: "Semua anggota sudah ngelist!",
    partialAnswered: (answered: number, total: number) =>
      `${answered} dari ${total} anggota sudah ngelist`,
    ordersList: "Daftar Ikut Makan",
    notEatingList: "Daftar Tidak Ikut Makan",
    pendingList: "Belum Memilih",
    portionBreakdown: "Rincian Porsi Belanja",
    totalPortions: (count: number) => `Total: ${count} porsi`,
    mainDishLabel: "Ikut",
    swapDishLabel: "Tidak Ikut",
    pingTelegram: "Kirim Pengingat Telegram",
    pingTelegramLoading: "Mengirim Pengingat...",
    pingTelegramSuccess: (count: number) => `Pengingat terkirim ke ${count} orang!`,
    pingTelegramEmpty: "Tidak ada anggota tertunda dengan Telegram ID.",
    pendingHint: "Klik nama anggota untuk mencatat status makan hari ini.",
    pendingBadgeTooltip: (name: string) => `Klik untuk catat pilihan ${name}`,
    recordResponseTitle: (name: string) => `Catat Pilihan: ${name}`,
    recordResponseSubtitle: (name: string, dish: string) =>
      `Tentukan apakah ${name} ikut makan menu ${dish} hari ini.`,
    recordEating: "Ikut Makan (Ya)",
    recordNotEating: "Tidak Ikut Makan (Tidak)",
    recordSave: "Simpan Pilihan",
    recordSaving: "Menyimpan…",
    recordSuccess: "Pilihan berhasil disimpan!",
  },
  whatsapp: {
    cardTitle: "Kirim Rekap WhatsApp",
    cardDescription: "Kirim daftar pesanan langsung ke WhatsApp atau salin format teksnya.",
    sendButton: "Kirim ke WhatsApp",
    copyButton: "Salin Format WA",
    copied: "Format WA Tersalin!",
    previewTitle: "Preview Teks WhatsApp:",
  },
  settings: {
    title: "Pengaturan",
    standingCutoff: "Batas waktu standar (JJ:MM)",
    reminderTime: "Jam pengingat (JJ:MM)",
    saved: "Tersimpan!",
    saveTimes: "Simpan jam",
    members: "Anggota",
    addMember: "Tambah anggota",
    name: "Nama",
    initialPin: "PIN awal",
    memberAdded: "Anggota ditambahkan!",
    add: "Tambah",
    newPin: "PIN baru",
    resetPin: "Reset PIN",
    pinUpdated: "PIN diperbarui",
    remove: "Hapus",
    defaultDishes: "Daftar menu bawaan",
    defaultDishesHint: "Menu-menu ini muncul sebagai saran saat Pak Yono membuat menu.",
    dishRemoved: "Menu dihapus!",
    addDish: "Tambah menu bawaan",
    editDish: "Edit menu bawaan",
    edit: "Edit",
    cancel: "Batal",
    saveDish: "Simpan perubahan",
    dishUpdated: "Menu berhasil diperbarui!",
    dishName: "Nama menu",
    dishNote: "Catatan lauk / template (opsional)",
    dishNotePlaceholder: "contoh: rendang, ayam bakar, sayur nangka, sambal ijo",
    dishNotePrefix: "Lauk / detail:",
    dishSubDishes: "Pilihan sub-menu / varian (opsional, pisahkan koma)",
    dishSubDishesPlaceholder: "contoh: Bakmi Goreng, Bakmi Godhog, Nasi Goreng",
    dishSubDishesPrefix: "Pilihan varian:",
    dishAdded: "Menu ditambahkan!",
    role: "Peran",
    roleMember: "Anggota (Pesan makan)",
    roleAdmin: "Admin (Kelola user dan menu)",
    adminBadge: "Admin",
    memberBadge: "Anggota",
    yonoBadge: "Koki",
    manageUsersHint: "Untuk menambah atau mengelola anggota kantor & admin, buka halaman Pengguna.",
    manageUsersBtn: "Buka Kelola Pengguna",
  },
  account: {
    updatePinTitle: "Ubah PIN Akun",
    updatePinDesc: "Perbarui PIN login kamu untuk menjaga keamanan akun.",
    currentPin: "PIN Saat Ini",
    currentPinPlaceholder: "Masukkan PIN lama",
    newPin: "PIN Baru",
    newPinPlaceholder: "PIN baru (min. 4 digit)",
    confirmPin: "Konfirmasi PIN Baru",
    confirmPinPlaceholder: "Ulangi PIN baru",
    updatePinBtn: "Simpan PIN Baru",
    updatingPin: "Menyimpan…",
    pinUpdatedSuccess: "PIN berhasil diperbarui!",
    errorCurrentPinWrong: "PIN saat ini salah.",
    errorPinMismatch: "Konfirmasi PIN baru tidak cocok.",
    errorAllFieldsRequired: "Semua kolom PIN wajib diisi.",
  },
  users: {
    title: "Kelola Pengguna",
    subtitle: "Daftar seluruh anggota dan admin katering kantor.",
    addUser: "Tambah Pengguna",
    name: "Nama",
    initialPin: "PIN awal (min. 4 digit)",
    role: "Peran",
    roleMember: "Anggota",
    roleAdmin: "Admin",
    roleYono: "Koki (Pak Yono)",
    changeRole: "Ganti Peran",
    roleUpdated: "Peran berhasil diperbarui!",
    newPin: "PIN Baru",
    resetPin: "Reset PIN",
    pinUpdated: "PIN berhasil diperbarui!",
    remove: "Hapus",
    confirmRemove: (name: string) => `Yakin ingin menghapus ${name}?`,
    userAdded: "Pengguna berhasil ditambahkan!",
    add: "Simpan Pengguna",
    totalUsers: (count: number) => `Total ${count} pengguna`,
    tableNo: "#",
    tableName: "Nama",
    tableRole: "Peran",
    tableTelegram: "Telegram ID",
    telegramId: "Telegram Chat ID",
    telegramPlaceholder: "contoh: 123456789",
    telegramHint: "Ketik /start di @yonocateringbot untuk tahu Chat ID Telegram.",
    telegramUpdated: "Telegram ID berhasil disimpan!",
    tableActions: "Aksi",
    searchPlaceholder: "Cari nama pengguna...",
    noUsersFound: "Pengguna tidak ditemukan.",
  },
  errors: {
    missingDay: "Hari tidak ditemukan.",
    swapRequired: "Pilihan wajib diisi.",
    noMenu: "Belum ada menu untuk hari ini.",
    locked: "Jawaban sudah terkunci hari ini.",
    dishRequired: "Menu wajib diisi.",
    dishExists: "Menu sudah ada dalam daftar.",
    dishNotFound: "Menu tidak ditemukan.",
    cutoffFormat: "Batas waktu harus format JJ:MM.",
    timeFormat: "Jam harus format JJ:MM.",
    namePinRequired: "Nama dan PIN wajib diisi.",
    pinMinLength: "PIN minimal 4 digit.",
    nameTaken: "Nama sudah dipakai.",
    memberNotFound: "Anggota tidak ditemukan.",
    memberPinRequired: "Anggota dan PIN wajib diisi.",
    cannotRemoveSelf: "Tidak bisa menghapus akun sendiri.",
    cannotRemoveYono: "Akun Pak Yono tidak bisa dihapus.",
    cannotChangeSelfRole: "Tidak bisa mengubah peran akun sendiri.",
    cannotChangeYonoRole: "Peran Pak Yono tidak bisa diubah.",
  },
  push: {
    morningTitle: "Selamat pagi, Pak Yono",
    morningBody: "Menu hari ini apa, Pak Yono?",
    menuTitle: "Menu diposting",
    menuBody: (dish: string, cutoff: string) =>
      `Hari ini: ${dish}. Jawab sebelum ${cutoff}.`,
    defaultTitle: "Yono Catering",
  },
  tally: {
    empty: "Belum ada pesanan",
    swap: "tidak ikut",
    portion: (count: number, dish: string) => `${count} porsi ${dish}`,
  },
} as const;
